version: '2'
services:
  web:
    image: nginx:latest
    ports:
    - "8080:80"
    volumes:
    - .:/app
    - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
    - php
  php:
    build: .
    volumes:
    - .:/app
    depends_on:
    - mysql
    links:
      - mysql
    env_file:
    - ./.docker-env
  mysql:
    container_name: mysql
    restart: always
    image: mysql:latest
    volumes:
    - slim_mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_DATABASE=slim
    - MYSQL_DATABASE_TEST=slim_test
    - MYSQL_USER=root
    - MYSQL_PASSWORD=123456
volumes:
  slim_mysql:
