<?php /**@var $docs string */ ?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Stamps server</title>
    <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
<h1 class="text-center">API</h1>
<div class="container">
    <script src="<?= $docs ?>"></script>
</div>
</body>
</html>
